/**
 * data.js — lookup tables for the meal planner.
 *
 * GENERATED from the tested reference implementation. Edit the lists here
 * freely, but keep the shapes identical (see grocery.js for consumers).
 *
 * The recipe library lives in recipes.js; the series colours live in
 * styles.css as --series-1..8 so they can swap for dark mode.
 */

/** Canonical aisle order used for grouping the grocery list. */
export const AISLES = [
  "Produce",
  "Meat & Seafood",
  "Dairy & Refrigerated",
  "Dry Pantry",
  "Sauces, Seasonings & Condiments",
  "Non-Recipe Household Additions"
];

export const AISLE_PRODUCE = "Produce";

export const AISLE_MEAT = "Meat & Seafood";

export const AISLE_DAIRY = "Dairy & Refrigerated";

export const AISLE_PANTRY = "Dry Pantry";

export const AISLE_SEASONINGS = "Sauces, Seasonings & Condiments";

export const AISLE_HOUSEHOLD = "Non-Recipe Household Additions";

export const DEFAULT_AISLE = "Dry Pantry";

/** keyword -> aisle. Longest keyword wins at match time. */
export const AISLE_KEYWORDS = {
  "onion": "Produce",
  "red onion": "Produce",
  "yellow onion": "Produce",
  "white onion": "Produce",
  "sweet onion": "Produce",
  "shallot": "Produce",
  "scallion": "Produce",
  "green onion": "Produce",
  "spring onion": "Produce",
  "leek": "Produce",
  "garlic": "Produce",
  "garlic clove": "Produce",
  "ginger": "Produce",
  "fresh ginger": "Produce",
  "galangal": "Produce",
  "tomato": "Produce",
  "cherry tomato": "Produce",
  "grape tomato": "Produce",
  "roma tomato": "Produce",
  "plum tomato": "Produce",
  "potato": "Produce",
  "russet potato": "Produce",
  "yukon gold potato": "Produce",
  "sweet potato": "Produce",
  "yam": "Produce",
  "carrot": "Produce",
  "celery": "Produce",
  "celery stalk": "Produce",
  "cucumber": "Produce",
  "radish": "Produce",
  "turnip": "Produce",
  "parsnip": "Produce",
  "beet": "Produce",
  "fennel": "Produce",
  "jicama": "Produce",
  "kohlrabi": "Produce",
  "rutabaga": "Produce",
  "bell pepper": "Produce",
  "red bell pepper": "Produce",
  "green bell pepper": "Produce",
  "yellow bell pepper": "Produce",
  "orange bell pepper": "Produce",
  "green pepper": "Produce",
  "sweet pepper": "Produce",
  "poblano": "Produce",
  "jalapeno": "Produce",
  "jalapeño": "Produce",
  "serrano": "Produce",
  "habanero": "Produce",
  "anaheim": "Produce",
  "chile pepper": "Produce",
  "chili pepper": "Produce",
  "fresh chile": "Produce",
  "lettuce": "Produce",
  "romaine": "Produce",
  "iceberg": "Produce",
  "spinach": "Produce",
  "baby spinach": "Produce",
  "kale": "Produce",
  "arugula": "Produce",
  "chard": "Produce",
  "swiss chard": "Produce",
  "collard greens": "Produce",
  "mustard greens": "Produce",
  "watercress": "Produce",
  "endive": "Produce",
  "radicchio": "Produce",
  "mesclun": "Produce",
  "spring mix": "Produce",
  "salad greens": "Produce",
  "mixed greens": "Produce",
  "sprouts": "Produce",
  "bean sprouts": "Produce",
  "cabbage": "Produce",
  "red cabbage": "Produce",
  "napa cabbage": "Produce",
  "bok choy": "Produce",
  "broccoli": "Produce",
  "broccolini": "Produce",
  "cauliflower": "Produce",
  "brussels sprouts": "Produce",
  "asparagus": "Produce",
  "green beans": "Produce",
  "snap peas": "Produce",
  "snow peas": "Produce",
  "okra": "Produce",
  "artichoke": "Produce",
  "zucchini": "Produce",
  "yellow squash": "Produce",
  "summer squash": "Produce",
  "butternut squash": "Produce",
  "acorn squash": "Produce",
  "spaghetti squash": "Produce",
  "pumpkin": "Produce",
  "eggplant": "Produce",
  "corn on the cob": "Produce",
  "ear of corn": "Produce",
  "fresh corn": "Produce",
  "mushroom": "Produce",
  "cremini": "Produce",
  "shiitake": "Produce",
  "portobello": "Produce",
  "button mushroom": "Produce",
  "lemon": "Produce",
  "lemon juice": "Produce",
  "lemon zest": "Produce",
  "lime": "Produce",
  "lime juice": "Produce",
  "lime zest": "Produce",
  "orange": "Produce",
  "orange juice": "Produce",
  "orange zest": "Produce",
  "grapefruit": "Produce",
  "apple": "Produce",
  "pear": "Produce",
  "banana": "Produce",
  "avocado": "Produce",
  "mango": "Produce",
  "pineapple": "Produce",
  "papaya": "Produce",
  "peach": "Produce",
  "nectarine": "Produce",
  "plum": "Produce",
  "apricot": "Produce",
  "cherries": "Produce",
  "fresh cherries": "Produce",
  "grapes": "Produce",
  "kiwi": "Produce",
  "pomegranate": "Produce",
  "melon": "Produce",
  "cantaloupe": "Produce",
  "honeydew": "Produce",
  "watermelon": "Produce",
  "strawberries": "Produce",
  "strawberry": "Produce",
  "blueberries": "Produce",
  "blueberry": "Produce",
  "raspberries": "Produce",
  "blackberries": "Produce",
  "cranberries": "Produce",
  "fresh herbs": "Produce",
  "cilantro": "Produce",
  "coriander leaves": "Produce",
  "parsley": "Produce",
  "flat-leaf parsley": "Produce",
  "fresh basil": "Produce",
  "basil leaves": "Produce",
  "fresh mint": "Produce",
  "mint leaves": "Produce",
  "fresh dill": "Produce",
  "fresh thyme": "Produce",
  "fresh rosemary": "Produce",
  "fresh sage": "Produce",
  "fresh oregano": "Produce",
  "fresh tarragon": "Produce",
  "chives": "Produce",
  "curry leaves": "Produce",
  "kaffir lime leaves": "Produce",
  "lemongrass": "Produce",
  "chicken": "Meat & Seafood",
  "chicken breast": "Meat & Seafood",
  "chicken breasts": "Meat & Seafood",
  "chicken thigh": "Meat & Seafood",
  "chicken thighs": "Meat & Seafood",
  "chicken drumstick": "Meat & Seafood",
  "chicken wings": "Meat & Seafood",
  "whole chicken": "Meat & Seafood",
  "rotisserie chicken": "Meat & Seafood",
  "ground chicken": "Meat & Seafood",
  "turkey": "Meat & Seafood",
  "ground turkey": "Meat & Seafood",
  "turkey breast": "Meat & Seafood",
  "duck": "Meat & Seafood",
  "cornish hen": "Meat & Seafood",
  "beef": "Meat & Seafood",
  "ground beef": "Meat & Seafood",
  "beef chuck": "Meat & Seafood",
  "chuck roast": "Meat & Seafood",
  "brisket": "Meat & Seafood",
  "steak": "Meat & Seafood",
  "ribeye": "Meat & Seafood",
  "sirloin": "Meat & Seafood",
  "flank steak": "Meat & Seafood",
  "skirt steak": "Meat & Seafood",
  "flat iron steak": "Meat & Seafood",
  "stew meat": "Meat & Seafood",
  "short ribs": "Meat & Seafood",
  "beef tenderloin": "Meat & Seafood",
  "pork": "Meat & Seafood",
  "ground pork": "Meat & Seafood",
  "pork chop": "Meat & Seafood",
  "pork chops": "Meat & Seafood",
  "pork loin": "Meat & Seafood",
  "pork shoulder": "Meat & Seafood",
  "pork belly": "Meat & Seafood",
  "pork tenderloin": "Meat & Seafood",
  "baby back ribs": "Meat & Seafood",
  "spare ribs": "Meat & Seafood",
  "bacon": "Meat & Seafood",
  "pancetta": "Meat & Seafood",
  "prosciutto": "Meat & Seafood",
  "ham": "Meat & Seafood",
  "ham hock": "Meat & Seafood",
  "sausage": "Meat & Seafood",
  "italian sausage": "Meat & Seafood",
  "breakfast sausage": "Meat & Seafood",
  "chorizo": "Meat & Seafood",
  "bratwurst": "Meat & Seafood",
  "kielbasa": "Meat & Seafood",
  "pepperoni": "Meat & Seafood",
  "salami": "Meat & Seafood",
  "hot dogs": "Meat & Seafood",
  "lamb": "Meat & Seafood",
  "ground lamb": "Meat & Seafood",
  "lamb chops": "Meat & Seafood",
  "leg of lamb": "Meat & Seafood",
  "veal": "Meat & Seafood",
  "bison": "Meat & Seafood",
  "venison": "Meat & Seafood",
  "rabbit": "Meat & Seafood",
  "goat": "Meat & Seafood",
  "fish": "Meat & Seafood",
  "fish fillet": "Meat & Seafood",
  "salmon": "Meat & Seafood",
  "salmon fillet": "Meat & Seafood",
  "tuna": "Meat & Seafood",
  "tuna steak": "Meat & Seafood",
  "sushi-grade tuna": "Meat & Seafood",
  "ahi tuna": "Meat & Seafood",
  "cod": "Meat & Seafood",
  "haddock": "Meat & Seafood",
  "halibut": "Meat & Seafood",
  "tilapia": "Meat & Seafood",
  "snapper": "Meat & Seafood",
  "sea bass": "Meat & Seafood",
  "trout": "Meat & Seafood",
  "mahi mahi": "Meat & Seafood",
  "swordfish": "Meat & Seafood",
  "catfish": "Meat & Seafood",
  "sardines": "Meat & Seafood",
  "shrimp": "Meat & Seafood",
  "prawns": "Meat & Seafood",
  "scallops": "Meat & Seafood",
  "crab": "Meat & Seafood",
  "crab meat": "Meat & Seafood",
  "lobster": "Meat & Seafood",
  "mussels": "Meat & Seafood",
  "clams": "Meat & Seafood",
  "oysters": "Meat & Seafood",
  "squid": "Meat & Seafood",
  "calamari": "Meat & Seafood",
  "octopus": "Meat & Seafood",
  "deli turkey": "Meat & Seafood",
  "deli ham": "Meat & Seafood",
  "rotisserie": "Meat & Seafood",
  "milk": "Dairy & Refrigerated",
  "whole milk": "Dairy & Refrigerated",
  "skim milk": "Dairy & Refrigerated",
  "buttermilk": "Dairy & Refrigerated",
  "evaporated milk": "Dairy & Refrigerated",
  "heavy cream": "Dairy & Refrigerated",
  "heavy whipping cream": "Dairy & Refrigerated",
  "whipping cream": "Dairy & Refrigerated",
  "cream": "Dairy & Refrigerated",
  "half-and-half": "Dairy & Refrigerated",
  "half and half": "Dairy & Refrigerated",
  "sour cream": "Dairy & Refrigerated",
  "creme fraiche": "Dairy & Refrigerated",
  "crème fraîche": "Dairy & Refrigerated",
  "whipped cream": "Dairy & Refrigerated",
  "clotted cream": "Dairy & Refrigerated",
  "butter": "Dairy & Refrigerated",
  "unsalted butter": "Dairy & Refrigerated",
  "salted butter": "Dairy & Refrigerated",
  "margarine": "Dairy & Refrigerated",
  "ghee": "Dairy & Refrigerated",
  "cheese": "Dairy & Refrigerated",
  "cheddar": "Dairy & Refrigerated",
  "cheddar cheese": "Dairy & Refrigerated",
  "mozzarella": "Dairy & Refrigerated",
  "parmesan": "Dairy & Refrigerated",
  "pecorino": "Dairy & Refrigerated",
  "romano": "Dairy & Refrigerated",
  "feta": "Dairy & Refrigerated",
  "goat cheese": "Dairy & Refrigerated",
  "ricotta": "Dairy & Refrigerated",
  "cream cheese": "Dairy & Refrigerated",
  "cottage cheese": "Dairy & Refrigerated",
  "mascarpone": "Dairy & Refrigerated",
  "gruyere": "Dairy & Refrigerated",
  "swiss cheese": "Dairy & Refrigerated",
  "provolone": "Dairy & Refrigerated",
  "monterey jack": "Dairy & Refrigerated",
  "pepper jack": "Dairy & Refrigerated",
  "gouda": "Dairy & Refrigerated",
  "brie": "Dairy & Refrigerated",
  "blue cheese": "Dairy & Refrigerated",
  "gorgonzola": "Dairy & Refrigerated",
  "halloumi": "Dairy & Refrigerated",
  "queso fresco": "Dairy & Refrigerated",
  "cotija": "Dairy & Refrigerated",
  "asiago": "Dairy & Refrigerated",
  "burrata": "Dairy & Refrigerated",
  "velveeta": "Dairy & Refrigerated",
  "yogurt": "Dairy & Refrigerated",
  "greek yogurt": "Dairy & Refrigerated",
  "plain yogurt": "Dairy & Refrigerated",
  "kefir": "Dairy & Refrigerated",
  "egg": "Dairy & Refrigerated",
  "eggs": "Dairy & Refrigerated",
  "egg white": "Dairy & Refrigerated",
  "egg whites": "Dairy & Refrigerated",
  "egg yolk": "Dairy & Refrigerated",
  "egg yolks": "Dairy & Refrigerated",
  "tofu": "Dairy & Refrigerated",
  "firm tofu": "Dairy & Refrigerated",
  "silken tofu": "Dairy & Refrigerated",
  "tempeh": "Dairy & Refrigerated",
  "seitan": "Dairy & Refrigerated",
  "almond milk": "Dairy & Refrigerated",
  "oat milk": "Dairy & Refrigerated",
  "soy milk": "Dairy & Refrigerated",
  "cashew milk": "Dairy & Refrigerated",
  "crescent rolls": "Dairy & Refrigerated",
  "puff pastry": "Dairy & Refrigerated",
  "pie crust": "Dairy & Refrigerated",
  "pizza dough": "Dairy & Refrigerated",
  "biscuit dough": "Dairy & Refrigerated",
  "wonton wrappers": "Dairy & Refrigerated",
  "refrigerated dough": "Dairy & Refrigerated",
  "flour": "Dry Pantry",
  "all-purpose flour": "Dry Pantry",
  "bread flour": "Dry Pantry",
  "cake flour": "Dry Pantry",
  "whole wheat flour": "Dry Pantry",
  "almond flour": "Dry Pantry",
  "cornmeal": "Dry Pantry",
  "polenta": "Dry Pantry",
  "grits": "Dry Pantry",
  "cornstarch": "Dry Pantry",
  "corn starch": "Dry Pantry",
  "tapioca starch": "Dry Pantry",
  "arrowroot": "Dry Pantry",
  "baking powder": "Dry Pantry",
  "baking soda": "Dry Pantry",
  "yeast": "Dry Pantry",
  "active dry yeast": "Dry Pantry",
  "sugar": "Dry Pantry",
  "granulated sugar": "Dry Pantry",
  "brown sugar": "Dry Pantry",
  "powdered sugar": "Dry Pantry",
  "confectioners sugar": "Dry Pantry",
  "coconut sugar": "Dry Pantry",
  "honey": "Dry Pantry",
  "maple syrup": "Dry Pantry",
  "molasses": "Dry Pantry",
  "corn syrup": "Dry Pantry",
  "agave": "Dry Pantry",
  "simple syrup": "Dry Pantry",
  "rice": "Dry Pantry",
  "white rice": "Dry Pantry",
  "brown rice": "Dry Pantry",
  "jasmine rice": "Dry Pantry",
  "basmati rice": "Dry Pantry",
  "arborio rice": "Dry Pantry",
  "wild rice": "Dry Pantry",
  "sushi rice": "Dry Pantry",
  "quinoa": "Dry Pantry",
  "couscous": "Dry Pantry",
  "bulgur": "Dry Pantry",
  "farro": "Dry Pantry",
  "barley": "Dry Pantry",
  "millet": "Dry Pantry",
  "buckwheat": "Dry Pantry",
  "pasta": "Dry Pantry",
  "spaghetti": "Dry Pantry",
  "penne": "Dry Pantry",
  "rigatoni": "Dry Pantry",
  "fettuccine": "Dry Pantry",
  "linguine": "Dry Pantry",
  "macaroni": "Dry Pantry",
  "elbow macaroni": "Dry Pantry",
  "lasagna noodles": "Dry Pantry",
  "orzo": "Dry Pantry",
  "ziti": "Dry Pantry",
  "egg noodles": "Dry Pantry",
  "rice noodles": "Dry Pantry",
  "ramen noodles": "Dry Pantry",
  "udon": "Dry Pantry",
  "soba": "Dry Pantry",
  "noodles": "Dry Pantry",
  "gnocchi": "Dry Pantry",
  "tortellini": "Dry Pantry",
  "bread": "Dry Pantry",
  "sandwich bread": "Dry Pantry",
  "baguette": "Dry Pantry",
  "sourdough": "Dry Pantry",
  "ciabatta": "Dry Pantry",
  "pita": "Dry Pantry",
  "naan": "Dry Pantry",
  "tortilla": "Dry Pantry",
  "tortillas": "Dry Pantry",
  "corn tortillas": "Dry Pantry",
  "flour tortillas": "Dry Pantry",
  "taco shells": "Dry Pantry",
  "burger buns": "Dry Pantry",
  "hot dog buns": "Dry Pantry",
  "buns": "Dry Pantry",
  "dinner rolls": "Dry Pantry",
  "bagels": "Dry Pantry",
  "english muffins": "Dry Pantry",
  "croutons": "Dry Pantry",
  "breadcrumbs": "Dry Pantry",
  "bread crumbs": "Dry Pantry",
  "panko": "Dry Pantry",
  "beans": "Dry Pantry",
  "black beans": "Dry Pantry",
  "kidney beans": "Dry Pantry",
  "pinto beans": "Dry Pantry",
  "cannellini beans": "Dry Pantry",
  "navy beans": "Dry Pantry",
  "garbanzo beans": "Dry Pantry",
  "chickpeas": "Dry Pantry",
  "refried beans": "Dry Pantry",
  "lentils": "Dry Pantry",
  "red lentils": "Dry Pantry",
  "split peas": "Dry Pantry",
  "edamame": "Dry Pantry",
  "frozen peas": "Dry Pantry",
  "frozen corn": "Dry Pantry",
  "frozen vegetables": "Dry Pantry",
  "broth": "Dry Pantry",
  "chicken broth": "Dry Pantry",
  "beef broth": "Dry Pantry",
  "vegetable broth": "Dry Pantry",
  "stock": "Dry Pantry",
  "chicken stock": "Dry Pantry",
  "beef stock": "Dry Pantry",
  "bone broth": "Dry Pantry",
  "bouillon cube": "Dry Pantry",
  "canned tomatoes": "Dry Pantry",
  "diced tomatoes": "Dry Pantry",
  "crushed tomatoes": "Dry Pantry",
  "tomato sauce": "Dry Pantry",
  "tomato paste": "Dry Pantry",
  "tomato puree": "Dry Pantry",
  "passata": "Dry Pantry",
  "fire roasted tomatoes": "Dry Pantry",
  "sun-dried tomatoes": "Dry Pantry",
  "canned pumpkin": "Dry Pantry",
  "coconut milk": "Dry Pantry",
  "coconut cream": "Dry Pantry",
  "canned corn": "Dry Pantry",
  "canned tuna": "Dry Pantry",
  "canned chicken": "Dry Pantry",
  "canned beans": "Dry Pantry",
  "canned chiles": "Dry Pantry",
  "green chiles": "Dry Pantry",
  "chipotle in adobo": "Dry Pantry",
  "artichoke hearts": "Dry Pantry",
  "oil": "Dry Pantry",
  "olive oil": "Dry Pantry",
  "extra-virgin olive oil": "Dry Pantry",
  "vegetable oil": "Dry Pantry",
  "canola oil": "Dry Pantry",
  "avocado oil": "Dry Pantry",
  "coconut oil": "Dry Pantry",
  "sunflower oil": "Dry Pantry",
  "peanut oil": "Dry Pantry",
  "cooking spray": "Dry Pantry",
  "shortening": "Dry Pantry",
  "lard": "Dry Pantry",
  "nuts": "Dry Pantry",
  "almonds": "Dry Pantry",
  "walnuts": "Dry Pantry",
  "pecans": "Dry Pantry",
  "cashews": "Dry Pantry",
  "peanuts": "Dry Pantry",
  "pistachios": "Dry Pantry",
  "hazelnuts": "Dry Pantry",
  "pine nuts": "Dry Pantry",
  "macadamia nuts": "Dry Pantry",
  "sesame seeds": "Dry Pantry",
  "sunflower seeds": "Dry Pantry",
  "pumpkin seeds": "Dry Pantry",
  "chia seeds": "Dry Pantry",
  "flaxseed": "Dry Pantry",
  "poppy seeds": "Dry Pantry",
  "hemp seeds": "Dry Pantry",
  "peanut butter": "Dry Pantry",
  "almond butter": "Dry Pantry",
  "tahini": "Dry Pantry",
  "nutella": "Dry Pantry",
  "jam": "Dry Pantry",
  "jelly": "Dry Pantry",
  "preserves": "Dry Pantry",
  "apple sauce": "Dry Pantry",
  "applesauce": "Dry Pantry",
  "raisins": "Dry Pantry",
  "dried cranberries": "Dry Pantry",
  "dried apricots": "Dry Pantry",
  "dates": "Dry Pantry",
  "prunes": "Dry Pantry",
  "dried figs": "Dry Pantry",
  "shredded coconut": "Dry Pantry",
  "coconut flakes": "Dry Pantry",
  "chocolate": "Dry Pantry",
  "chocolate chips": "Dry Pantry",
  "dark chocolate": "Dry Pantry",
  "white chocolate": "Dry Pantry",
  "cocoa powder": "Dry Pantry",
  "cacao": "Dry Pantry",
  "marshmallows": "Dry Pantry",
  "sprinkles": "Dry Pantry",
  "oats": "Dry Pantry",
  "rolled oats": "Dry Pantry",
  "steel cut oats": "Dry Pantry",
  "granola": "Dry Pantry",
  "cereal": "Dry Pantry",
  "crackers": "Dry Pantry",
  "tortilla chips": "Dry Pantry",
  "potato chips": "Dry Pantry",
  "pretzels": "Dry Pantry",
  "popcorn kernels": "Dry Pantry",
  "gelatin": "Dry Pantry",
  "protein powder": "Dry Pantry",
  "wine": "Dry Pantry",
  "red wine": "Dry Pantry",
  "white wine": "Dry Pantry",
  "dry white wine": "Dry Pantry",
  "sherry": "Dry Pantry",
  "beer": "Dry Pantry",
  "rum": "Dry Pantry",
  "bourbon": "Dry Pantry",
  "vodka": "Dry Pantry",
  "mirin": "Dry Pantry",
  "sake": "Dry Pantry",
  "coffee": "Dry Pantry",
  "coffee beans": "Dry Pantry",
  "ground coffee": "Dry Pantry",
  "tea": "Dry Pantry",
  "tea bags": "Dry Pantry",
  "sparkling water": "Dry Pantry",
  "club soda": "Dry Pantry",
  "juice": "Dry Pantry",
  "apple juice": "Dry Pantry",
  "salt": "Sauces, Seasonings & Condiments",
  "kosher salt": "Sauces, Seasonings & Condiments",
  "sea salt": "Sauces, Seasonings & Condiments",
  "table salt": "Sauces, Seasonings & Condiments",
  "flaky salt": "Sauces, Seasonings & Condiments",
  "pepper": "Sauces, Seasonings & Condiments",
  "black pepper": "Sauces, Seasonings & Condiments",
  "ground black pepper": "Sauces, Seasonings & Condiments",
  "white pepper": "Sauces, Seasonings & Condiments",
  "peppercorns": "Sauces, Seasonings & Condiments",
  "lemon pepper": "Sauces, Seasonings & Condiments",
  "cumin": "Sauces, Seasonings & Condiments",
  "ground cumin": "Sauces, Seasonings & Condiments",
  "coriander": "Sauces, Seasonings & Condiments",
  "ground coriander": "Sauces, Seasonings & Condiments",
  "paprika": "Sauces, Seasonings & Condiments",
  "smoked paprika": "Sauces, Seasonings & Condiments",
  "sweet paprika": "Sauces, Seasonings & Condiments",
  "chili powder": "Sauces, Seasonings & Condiments",
  "cayenne": "Sauces, Seasonings & Condiments",
  "cayenne pepper": "Sauces, Seasonings & Condiments",
  "red pepper flakes": "Sauces, Seasonings & Condiments",
  "crushed red pepper": "Sauces, Seasonings & Condiments",
  "chipotle powder": "Sauces, Seasonings & Condiments",
  "ancho chili powder": "Sauces, Seasonings & Condiments",
  "turmeric": "Sauces, Seasonings & Condiments",
  "curry powder": "Sauces, Seasonings & Condiments",
  "garam masala": "Sauces, Seasonings & Condiments",
  "five spice": "Sauces, Seasonings & Condiments",
  "cinnamon": "Sauces, Seasonings & Condiments",
  "ground cinnamon": "Sauces, Seasonings & Condiments",
  "cinnamon stick": "Sauces, Seasonings & Condiments",
  "nutmeg": "Sauces, Seasonings & Condiments",
  "cloves": "Sauces, Seasonings & Condiments",
  "ground cloves": "Sauces, Seasonings & Condiments",
  "allspice": "Sauces, Seasonings & Condiments",
  "cardamom": "Sauces, Seasonings & Condiments",
  "star anise": "Sauces, Seasonings & Condiments",
  "fennel seeds": "Sauces, Seasonings & Condiments",
  "mustard seeds": "Sauces, Seasonings & Condiments",
  "celery seed": "Sauces, Seasonings & Condiments",
  "caraway seeds": "Sauces, Seasonings & Condiments",
  "juniper berries": "Sauces, Seasonings & Condiments",
  "saffron": "Sauces, Seasonings & Condiments",
  "sumac": "Sauces, Seasonings & Condiments",
  "za'atar": "Sauces, Seasonings & Condiments",
  "zaatar": "Sauces, Seasonings & Condiments",
  "dried oregano": "Sauces, Seasonings & Condiments",
  "oregano": "Sauces, Seasonings & Condiments",
  "dried basil": "Sauces, Seasonings & Condiments",
  "dried thyme": "Sauces, Seasonings & Condiments",
  "thyme": "Sauces, Seasonings & Condiments",
  "dried rosemary": "Sauces, Seasonings & Condiments",
  "rosemary": "Sauces, Seasonings & Condiments",
  "dried sage": "Sauces, Seasonings & Condiments",
  "sage": "Sauces, Seasonings & Condiments",
  "marjoram": "Sauces, Seasonings & Condiments",
  "tarragon": "Sauces, Seasonings & Condiments",
  "dill weed": "Sauces, Seasonings & Condiments",
  "bay leaf": "Sauces, Seasonings & Condiments",
  "bay leaves": "Sauces, Seasonings & Condiments",
  "italian seasoning": "Sauces, Seasonings & Condiments",
  "herbes de provence": "Sauces, Seasonings & Condiments",
  "poultry seasoning": "Sauces, Seasonings & Condiments",
  "onion powder": "Sauces, Seasonings & Condiments",
  "garlic powder": "Sauces, Seasonings & Condiments",
  "garlic salt": "Sauces, Seasonings & Condiments",
  "celery salt": "Sauces, Seasonings & Condiments",
  "old bay": "Sauces, Seasonings & Condiments",
  "cajun seasoning": "Sauces, Seasonings & Condiments",
  "creole seasoning": "Sauces, Seasonings & Condiments",
  "jerk seasoning": "Sauces, Seasonings & Condiments",
  "taco seasoning": "Sauces, Seasonings & Condiments",
  "ranch seasoning": "Sauces, Seasonings & Condiments",
  "everything bagel seasoning": "Sauces, Seasonings & Condiments",
  "seasoning": "Sauces, Seasonings & Condiments",
  "spice blend": "Sauces, Seasonings & Condiments",
  "msg": "Sauces, Seasonings & Condiments",
  "bouillon": "Sauces, Seasonings & Condiments",
  "better than bouillon": "Sauces, Seasonings & Condiments",
  "vanilla extract": "Sauces, Seasonings & Condiments",
  "vanilla": "Sauces, Seasonings & Condiments",
  "almond extract": "Sauces, Seasonings & Condiments",
  "vanilla bean": "Sauces, Seasonings & Condiments",
  "food coloring": "Sauces, Seasonings & Condiments",
  "liquid smoke": "Sauces, Seasonings & Condiments",
  "rose water": "Sauces, Seasonings & Condiments",
  "soy sauce": "Sauces, Seasonings & Condiments",
  "low-sodium soy sauce": "Sauces, Seasonings & Condiments",
  "tamari": "Sauces, Seasonings & Condiments",
  "coconut aminos": "Sauces, Seasonings & Condiments",
  "fish sauce": "Sauces, Seasonings & Condiments",
  "oyster sauce": "Sauces, Seasonings & Condiments",
  "hoisin sauce": "Sauces, Seasonings & Condiments",
  "hoisin": "Sauces, Seasonings & Condiments",
  "teriyaki sauce": "Sauces, Seasonings & Condiments",
  "ponzu": "Sauces, Seasonings & Condiments",
  "sriracha": "Sauces, Seasonings & Condiments",
  "hot sauce": "Sauces, Seasonings & Condiments",
  "tabasco": "Sauces, Seasonings & Condiments",
  "chili garlic sauce": "Sauces, Seasonings & Condiments",
  "sambal oelek": "Sauces, Seasonings & Condiments",
  "gochujang": "Sauces, Seasonings & Condiments",
  "harissa": "Sauces, Seasonings & Condiments",
  "curry paste": "Sauces, Seasonings & Condiments",
  "red curry paste": "Sauces, Seasonings & Condiments",
  "green curry paste": "Sauces, Seasonings & Condiments",
  "miso": "Sauces, Seasonings & Condiments",
  "miso paste": "Sauces, Seasonings & Condiments",
  "worcestershire sauce": "Sauces, Seasonings & Condiments",
  "worcestershire": "Sauces, Seasonings & Condiments",
  "vinegar": "Sauces, Seasonings & Condiments",
  "white vinegar": "Sauces, Seasonings & Condiments",
  "red wine vinegar": "Sauces, Seasonings & Condiments",
  "white wine vinegar": "Sauces, Seasonings & Condiments",
  "balsamic vinegar": "Sauces, Seasonings & Condiments",
  "apple cider vinegar": "Sauces, Seasonings & Condiments",
  "rice vinegar": "Sauces, Seasonings & Condiments",
  "sherry vinegar": "Sauces, Seasonings & Condiments",
  "malt vinegar": "Sauces, Seasonings & Condiments",
  "mustard": "Sauces, Seasonings & Condiments",
  "dijon mustard": "Sauces, Seasonings & Condiments",
  "yellow mustard": "Sauces, Seasonings & Condiments",
  "whole grain mustard": "Sauces, Seasonings & Condiments",
  "ketchup": "Sauces, Seasonings & Condiments",
  "mayonnaise": "Sauces, Seasonings & Condiments",
  "mayo": "Sauces, Seasonings & Condiments",
  "aioli": "Sauces, Seasonings & Condiments",
  "tartar sauce": "Sauces, Seasonings & Condiments",
  "bbq sauce": "Sauces, Seasonings & Condiments",
  "barbecue sauce": "Sauces, Seasonings & Condiments",
  "steak sauce": "Sauces, Seasonings & Condiments",
  "cocktail sauce": "Sauces, Seasonings & Condiments",
  "ranch dressing": "Sauces, Seasonings & Condiments",
  "caesar dressing": "Sauces, Seasonings & Condiments",
  "salad dressing": "Sauces, Seasonings & Condiments",
  "italian dressing": "Sauces, Seasonings & Condiments",
  "vinaigrette": "Sauces, Seasonings & Condiments",
  "pesto": "Sauces, Seasonings & Condiments",
  "chimichurri": "Sauces, Seasonings & Condiments",
  "salsa": "Sauces, Seasonings & Condiments",
  "salsa verde": "Sauces, Seasonings & Condiments",
  "enchilada sauce": "Sauces, Seasonings & Condiments",
  "marinara": "Sauces, Seasonings & Condiments",
  "marinara sauce": "Sauces, Seasonings & Condiments",
  "pasta sauce": "Sauces, Seasonings & Condiments",
  "alfredo sauce": "Sauces, Seasonings & Condiments",
  "buffalo sauce": "Sauces, Seasonings & Condiments",
  "pickles": "Sauces, Seasonings & Condiments",
  "pickle relish": "Sauces, Seasonings & Condiments",
  "relish": "Sauces, Seasonings & Condiments",
  "capers": "Sauces, Seasonings & Condiments",
  "olives": "Sauces, Seasonings & Condiments",
  "kalamata olives": "Sauces, Seasonings & Condiments",
  "green olives": "Sauces, Seasonings & Condiments",
  "pepperoncini": "Sauces, Seasonings & Condiments",
  "horseradish": "Sauces, Seasonings & Condiments",
  "wasabi": "Sauces, Seasonings & Condiments",
  "sauerkraut": "Sauces, Seasonings & Condiments",
  "kimchi": "Sauces, Seasonings & Condiments",
  "chutney": "Sauces, Seasonings & Condiments",
  "nutritional yeast": "Sauces, Seasonings & Condiments",
  "furikake": "Sauces, Seasonings & Condiments",
  "duck sauce": "Sauces, Seasonings & Condiments",
  "maggi": "Sauces, Seasonings & Condiments",
  "paper towels": "Non-Recipe Household Additions",
  "paper towel": "Non-Recipe Household Additions",
  "toilet paper": "Non-Recipe Household Additions",
  "napkins": "Non-Recipe Household Additions",
  "trash bags": "Non-Recipe Household Additions",
  "garbage bags": "Non-Recipe Household Additions",
  "aluminum foil": "Non-Recipe Household Additions",
  "foil": "Non-Recipe Household Additions",
  "plastic wrap": "Non-Recipe Household Additions",
  "parchment paper": "Non-Recipe Household Additions",
  "wax paper": "Non-Recipe Household Additions",
  "zip-top bags": "Non-Recipe Household Additions",
  "ziploc bags": "Non-Recipe Household Additions",
  "sandwich bags": "Non-Recipe Household Additions",
  "food storage bags": "Non-Recipe Household Additions",
  "dish soap": "Non-Recipe Household Additions",
  "dishwasher detergent": "Non-Recipe Household Additions",
  "dishwasher pods": "Non-Recipe Household Additions",
  "laundry detergent": "Non-Recipe Household Additions",
  "fabric softener": "Non-Recipe Household Additions",
  "dryer sheets": "Non-Recipe Household Additions",
  "hand soap": "Non-Recipe Household Additions",
  "body wash": "Non-Recipe Household Additions",
  "shampoo": "Non-Recipe Household Additions",
  "conditioner": "Non-Recipe Household Additions",
  "toothpaste": "Non-Recipe Household Additions",
  "toothbrush": "Non-Recipe Household Additions",
  "deodorant": "Non-Recipe Household Additions",
  "razors": "Non-Recipe Household Additions",
  "floss": "Non-Recipe Household Additions",
  "mouthwash": "Non-Recipe Household Additions",
  "all-purpose cleaner": "Non-Recipe Household Additions",
  "bleach": "Non-Recipe Household Additions",
  "disinfectant wipes": "Non-Recipe Household Additions",
  "sponges": "Non-Recipe Household Additions",
  "scrub brush": "Non-Recipe Household Additions",
  "rubber gloves": "Non-Recipe Household Additions",
  "light bulbs": "Non-Recipe Household Additions",
  "batteries": "Non-Recipe Household Additions",
  "tissues": "Non-Recipe Household Additions",
  "cotton swabs": "Non-Recipe Household Additions",
  "band-aids": "Non-Recipe Household Additions",
  "sunscreen": "Non-Recipe Household Additions",
  "lotion": "Non-Recipe Household Additions",
  "diapers": "Non-Recipe Household Additions",
  "baby wipes": "Non-Recipe Household Additions",
  "pet food": "Non-Recipe Household Additions",
  "dog food": "Non-Recipe Household Additions",
  "cat food": "Non-Recipe Household Additions",
  "cat litter": "Non-Recipe Household Additions",
  "air freshener": "Non-Recipe Household Additions",
  "candles": "Non-Recipe Household Additions"
};

/** Spelling/abbreviation -> canonical unit. */
export const UNIT_ALIASES = {
  "teaspoon": "tsp",
  "teaspoons": "tsp",
  "tsp": "tsp",
  "tsps": "tsp",
  "tsp.": "tsp",
  "teasp": "tsp",
  "tablespoon": "tbsp",
  "tablespoons": "tbsp",
  "tbsp": "tbsp",
  "tbsps": "tbsp",
  "tbsp.": "tbsp",
  "tbs": "tbsp",
  "tblsp": "tbsp",
  "cup": "cup",
  "cups": "cup",
  "pint": "pint",
  "pints": "pint",
  "pt": "pint",
  "quart": "quart",
  "quarts": "quart",
  "qt": "quart",
  "qts": "quart",
  "gallon": "gallon",
  "gallons": "gallon",
  "gal": "gallon",
  "fluid ounce": "fl oz",
  "fluid ounces": "fl oz",
  "fl oz": "fl oz",
  "fl. oz.": "fl oz",
  "fl oz.": "fl oz",
  "floz": "fl oz",
  "milliliter": "ml",
  "milliliters": "ml",
  "millilitre": "ml",
  "millilitres": "ml",
  "ml": "ml",
  "ml.": "ml",
  "cc": "ml",
  "liter": "l",
  "liters": "l",
  "litre": "l",
  "litres": "l",
  "l": "l",
  "ounce": "oz",
  "ounces": "oz",
  "oz": "oz",
  "oz.": "oz",
  "pound": "lb",
  "pounds": "lb",
  "lb": "lb",
  "lbs": "lb",
  "lb.": "lb",
  "gram": "g",
  "grams": "g",
  "g": "g",
  "gr": "g",
  "gm": "g",
  "kilogram": "kg",
  "kilograms": "kg",
  "kg": "kg",
  "kgs": "kg",
  "clove": "clove",
  "cloves": "clove",
  "can": "can",
  "cans": "can",
  "jar": "jar",
  "jars": "jar",
  "bottle": "bottle",
  "bottles": "bottle",
  "package": "package",
  "packages": "package",
  "pkg": "package",
  "pkgs": "package",
  "packet": "packet",
  "packets": "packet",
  "container": "container",
  "containers": "container",
  "box": "box",
  "boxes": "box",
  "bag": "bag",
  "bags": "bag",
  "block": "block",
  "blocks": "block",
  "slice": "slice",
  "slices": "slice",
  "stalk": "stalk",
  "stalks": "stalk",
  "sprig": "sprig",
  "sprigs": "sprig",
  "bunch": "bunch",
  "bunches": "bunch",
  "head": "head",
  "heads": "head",
  "ear": "ear",
  "ears": "ear",
  "piece": "piece",
  "pieces": "piece",
  "pinch": "pinch",
  "pinches": "pinch",
  "dash": "dash",
  "dashes": "dash",
  "drop": "drop",
  "drops": "drop",
  "sheet": "sheet",
  "sheets": "sheet",
  "stick": "stick",
  "sticks": "stick",
  "fillet": "fillet",
  "fillets": "fillet",
  "filet": "fillet",
  "breast": "breast",
  "breasts": "breast",
  "thigh": "thigh",
  "thighs": "thigh",
  "rib": "rib",
  "ribs": "rib",
  "handful": "handful",
  "handfuls": "handful",
  "loaf": "loaf",
  "loaves": "loaf",
  "wedge": "wedge",
  "wedges": "wedge",
  "strip": "strip",
  "strips": "strip",
  "leaf": "leaf",
  "leaves": "leaf",
  "scoop": "scoop",
  "scoops": "scoop",
  "square": "square",
  "squares": "square",
  "roll": "roll",
  "rolls": "roll"
};

/** Canonical unit -> conversion family and factor in that family's base unit. */
export const UNIT_FAMILIES = {
  "tsp": {
    "family": "volume",
    "factor": 1.0
  },
  "tbsp": {
    "family": "volume",
    "factor": 3.0
  },
  "fl oz": {
    "family": "volume",
    "factor": 6.0
  },
  "cup": {
    "family": "volume",
    "factor": 48.0
  },
  "pint": {
    "family": "volume",
    "factor": 96.0
  },
  "quart": {
    "family": "volume",
    "factor": 192.0
  },
  "gallon": {
    "family": "volume",
    "factor": 768.0
  },
  "ml": {
    "family": "volume",
    "factor": 0.2028841
  },
  "l": {
    "family": "volume",
    "factor": 202.8841
  },
  "g": {
    "family": "weight",
    "factor": 1.0
  },
  "kg": {
    "family": "weight",
    "factor": 1000.0
  },
  "oz": {
    "family": "weight",
    "factor": 28.3495
  },
  "lb": {
    "family": "weight",
    "factor": 453.592
  }
};

export const METRIC_UNITS = [
  "g",
  "kg",
  "l",
  "ml"
];

export const NO_PLURAL_UNITS = [
  "fl oz",
  "g",
  "kg",
  "l",
  "lb",
  "ml",
  "oz",
  "tbsp",
  "tsp"
];

export const IRREGULAR_PLURALS = {
  "loaf": "loaves",
  "leaf": "leaves"
};

/** Units you buy whole: rounded up on the grocery list. */
export const DISCRETE_UNITS = [
  "",
  "bag",
  "bottle",
  "box",
  "breast",
  "bunch",
  "can",
  "clove",
  "container",
  "ear",
  "fillet",
  "head",
  "jar",
  "leaf",
  "loaf",
  "package",
  "packet",
  "piece",
  "rib",
  "roll",
  "scoop",
  "sheet",
  "slice",
  "sprig",
  "square",
  "stalk",
  "stick",
  "strip",
  "thigh",
  "wedge"
];

/** Measure words lifted out of a name so '3 garlic cloves' matches '3 cloves garlic'. */
export const NAME_UNIT_WORDS = [
  "bag",
  "block",
  "bottle",
  "box",
  "bunch",
  "can",
  "clove",
  "container",
  "ear",
  "head",
  "jar",
  "loaf",
  "package",
  "packet",
  "sheet",
  "slice",
  "sprig",
  "stalk",
  "stick",
  "strip",
  "wedge"
];

/** Dropped when building an ingredient merge key. */
export const NOISE_WORDS = [
  "a",
  "about",
  "all-natural",
  "an",
  "and",
  "approximately",
  "as",
  "at",
  "baby",
  "bag",
  "bone-in",
  "boneless",
  "bottle",
  "box",
  "bunch",
  "can",
  "chilled",
  "chopped",
  "clove",
  "coarsely",
  "cold",
  "container",
  "cooked",
  "cored",
  "crumbled",
  "cubed",
  "dash",
  "divided",
  "drained",
  "drop",
  "dry",
  "ear",
  "extra",
  "fat-free",
  "finely",
  "for",
  "fresh",
  "freshly",
  "garnish",
  "good",
  "grated",
  "halved",
  "handful",
  "head",
  "heaping",
  "homemade",
  "hot",
  "if",
  "in",
  "inch",
  "inches",
  "into",
  "jar",
  "julienned",
  "jumbo",
  "large",
  "lean",
  "leftover",
  "lightly",
  "low-fat",
  "low-sodium",
  "mashed",
  "medium",
  "melted",
  "minced",
  "mini",
  "more",
  "natural",
  "needed",
  "non-fat",
  "nonfat",
  "of",
  "on",
  "optional",
  "or",
  "organic",
  "package",
  "packed",
  "packet",
  "patted",
  "peeled",
  "piece",
  "pieces",
  "pinch",
  "pitted",
  "plus",
  "preferably",
  "quality",
  "quartered",
  "raw",
  "reduced-fat",
  "reduced-sodium",
  "rinsed",
  "room",
  "roughly",
  "salted",
  "scant",
  "scoop",
  "scrubbed",
  "seeded",
  "serve",
  "serving",
  "shredded",
  "skin-on",
  "skinless",
  "slice",
  "sliced",
  "small",
  "softened",
  "sprig",
  "stalk",
  "stemmed",
  "stick",
  "store-bought",
  "strip",
  "taste",
  "temperature",
  "thawed",
  "the",
  "thinly",
  "to",
  "topping",
  "trimmed",
  "uncooked",
  "unsalted",
  "very",
  "warm",
  "warmed",
  "washed",
  "wedge",
  "whole",
  "with"
];

export const TRAILING_PHRASES = [
  "to taste",
  "or to taste",
  "as needed",
  "if needed",
  "for serving",
  "for garnish",
  "for topping",
  "for drizzling",
  "for brushing",
  "for frying",
  "for greasing",
  "or more to taste",
  "divided",
  "plus more for serving",
  "plus more",
  "optional"
];

/** Dropped from grocery-list display names. */
export const SIZE_WORDS = [
  "extra",
  "extra-large",
  "heaping",
  "jumbo",
  "large",
  "medium",
  "ripe",
  "scant",
  "small",
  "xl"
];

export const UNICODE_FRACTIONS = {
  "½": 0.5,
  "⅓": 0.3333333333333333,
  "⅔": 0.6666666666666666,
  "¼": 0.25,
  "¾": 0.75,
  "⅕": 0.2,
  "⅖": 0.4,
  "⅗": 0.6,
  "⅘": 0.8,
  "⅙": 0.16666666666666666,
  "⅚": 0.8333333333333334,
  "⅛": 0.125,
  "⅜": 0.375,
  "⅝": 0.625,
  "⅞": 0.875,
  "⅐": 0.14285714285714285,
  "⅑": 0.1111111111111111,
  "⅒": 0.1
};

/**
 * Number of distinct recipe colours. Slots map to the CSS custom properties
 * --series-1 .. --series-8, which are validated for colour-vision deficiency
 * in both light and dark mode. Recipes past the eighth reuse a colour; the
 * number printed inside each chip is what actually identifies the recipe.
 */
export const SERIES_COUNT = 8;
