/**
 * recipes.js — the built-in recipe library.
 *
 * Sixty recipes across eight categories, each with a one-line description and
 * a realistic ingredient list written the way recipes actually write them, so
 * the parser and the aisle sorter get a proper workout.
 *
 * Shape: { title, category, description, servings, ingredients: [string] }
 *
 * Add your own here if you like — anything in this list shows up under
 * "Add the starter recipes". Keep `category` to one of CATEGORIES below, or
 * add a new one to that array first.
 */

export const CATEGORIES = [
  'Chicken',
  'Beef & Pork',
  'Seafood',
  'Vegetarian',
  'Pasta',
  'Soups & Stews',
  'Breakfast',
  'Salads & Bowls',
];

export const RECIPE_LIBRARY = [
  // ----------------------------------------------------------------- Chicken
  {
    title: 'Garlic Butter Chicken & Rice',
    category: 'Chicken',
    description: 'One pan, buttery garlic sauce, rice cooked right in the drippings.',
    servings: 4,
    ingredients: [
      '1.5 pounds boneless skinless chicken thighs',
      '3 tablespoons unsalted butter',
      '4 cloves garlic, minced',
      '1 yellow onion, diced',
      '1.5 cups jasmine rice',
      '3 cups chicken broth',
      '2 tablespoons olive oil',
      '1 lemon, juiced',
      '2 tablespoons fresh parsley, chopped',
      '1 teaspoon kosher salt',
      '1/2 teaspoon black pepper',
      '1 teaspoon smoked paprika',
    ],
  },
  {
    title: 'Lemon Herb Roasted Chicken Thighs',
    category: 'Chicken',
    description: 'Crisp-skinned thighs roasted over potatoes with lemon and thyme.',
    servings: 4,
    ingredients: [
      '8 bone-in chicken thighs',
      '1.5 pounds baby potatoes, halved',
      '2 lemons, sliced',
      '4 cloves garlic, smashed',
      '3 tablespoons olive oil',
      '1 tablespoon fresh thyme',
      '1 teaspoon dried oregano',
      '1.5 teaspoons kosher salt',
      '1/2 teaspoon black pepper',
    ],
  },
  {
    title: 'Honey Mustard Sheet Pan Chicken',
    category: 'Chicken',
    description: 'Sticky honey mustard chicken with broccoli and sweet potato.',
    servings: 4,
    ingredients: [
      '4 boneless skinless chicken breasts',
      '2 sweet potatoes, cubed',
      '1 pound broccoli florets',
      '3 tablespoons dijon mustard',
      '3 tablespoons honey',
      '2 tablespoons olive oil',
      '2 cloves garlic, minced',
      '1 teaspoon kosher salt',
      '1/2 teaspoon black pepper',
    ],
  },
  {
    title: 'Chicken Fajitas',
    category: 'Chicken',
    description: 'Charred peppers and onions with warm tortillas and lime.',
    servings: 4,
    ingredients: [
      '1.5 pounds chicken breast, sliced',
      '2 bell peppers, sliced',
      '1 red onion, sliced',
      '8 flour tortillas',
      '1 lime, cut into wedges',
      '1 avocado, sliced',
      '1/2 cup sour cream',
      '3 tablespoons olive oil',
      '1 tablespoon chili powder',
      '2 teaspoons ground cumin',
      '1 teaspoon smoked paprika',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'Creamy Tuscan Chicken',
    category: 'Chicken',
    description: 'Sun-dried tomatoes and spinach in a parmesan cream sauce.',
    servings: 4,
    ingredients: [
      '4 boneless skinless chicken breasts',
      '1 cup heavy cream',
      '1/2 cup grated parmesan',
      '3 cups baby spinach',
      '1/2 cup sun-dried tomatoes, chopped',
      '4 cloves garlic, minced',
      '2 tablespoons olive oil',
      '1 tablespoon unsalted butter',
      '1 teaspoon italian seasoning',
      '1 teaspoon kosher salt',
      '1/2 teaspoon black pepper',
    ],
  },
  {
    title: 'Teriyaki Chicken Rice Bowls',
    category: 'Chicken',
    description: 'Glossy teriyaki chicken over rice with steamed broccoli.',
    servings: 4,
    ingredients: [
      '1.5 pounds chicken thighs, cubed',
      '1.5 cups jasmine rice',
      '1 pound broccoli florets',
      '1/3 cup soy sauce',
      '3 tablespoons honey',
      '2 tablespoons rice vinegar',
      '1 tablespoon fresh ginger, grated',
      '3 cloves garlic, minced',
      '1 tablespoon cornstarch',
      '1 tablespoon sesame seeds',
      '2 green onions, sliced',
    ],
  },
  {
    title: 'Buffalo Chicken Wraps',
    category: 'Chicken',
    description: 'Twenty-minute wraps with crunchy slaw and blue cheese.',
    servings: 4,
    ingredients: [
      '1 pound cooked chicken breast, shredded',
      '4 large flour tortillas',
      '1/3 cup buffalo sauce',
      '2 cups shredded lettuce',
      '1 carrot, grated',
      '1/2 cup blue cheese',
      '1/3 cup ranch dressing',
      '2 celery stalks, sliced',
    ],
  },
  {
    title: 'Chicken Piccata',
    category: 'Chicken',
    description: 'Pan-fried cutlets in a bright lemon caper butter sauce.',
    servings: 4,
    ingredients: [
      '4 chicken breasts, pounded thin',
      '1/2 cup all-purpose flour',
      '3 tablespoons unsalted butter',
      '2 tablespoons olive oil',
      '1/2 cup chicken broth',
      '2 lemons, juiced',
      '3 tablespoons capers, drained',
      '2 cloves garlic, minced',
      '2 tablespoons fresh parsley, chopped',
      '1 teaspoon kosher salt',
      '1/2 teaspoon black pepper',
    ],
  },

  // ------------------------------------------------------------ Beef & Pork
  {
    title: 'Weeknight Beef Tacos',
    category: 'Beef & Pork',
    description: 'The reliable Tuesday standby, on the table in twenty minutes.',
    servings: 4,
    ingredients: [
      '1 pound ground beef',
      '1 yellow onion, finely chopped',
      '2 cloves garlic, minced',
      '8 corn tortillas',
      '1 cup shredded cheddar cheese',
      '2 roma tomatoes, diced',
      '1 avocado, sliced',
      '1/2 cup sour cream',
      '1/4 cup fresh cilantro, chopped',
      '1 lime, cut into wedges',
      '1 tablespoon chili powder',
      '2 teaspoons ground cumin',
      '1 teaspoon kosher salt',
      '1/2 cup salsa',
    ],
  },
  {
    title: 'Smash Burgers & Slaw',
    category: 'Beef & Pork',
    description: 'Thin crispy-edged patties with a tangy vinegar slaw.',
    servings: 4,
    ingredients: [
      '1.5 pounds ground beef',
      '4 burger buns',
      '4 slices cheddar cheese',
      '1 red onion, thinly sliced',
      '2 cups shredded cabbage',
      '1 carrot, grated',
      '1/3 cup mayonnaise',
      '1 tablespoon apple cider vinegar',
      '2 tablespoons ketchup',
      '1 tablespoon dijon mustard',
      '2 tablespoons unsalted butter',
      '1 teaspoon kosher salt',
      '1/2 teaspoon black pepper',
    ],
  },
  {
    title: 'Classic Beef Chili',
    category: 'Beef & Pork',
    description: 'Slow-simmered and even better the next day.',
    servings: 6,
    ingredients: [
      '2 pounds ground beef',
      '1 yellow onion, diced',
      '1 red bell pepper, diced',
      '4 cloves garlic, minced',
      '2 cans kidney beans, drained',
      '1 can black beans, drained',
      '1 (28 ounce) can crushed tomatoes',
      '2 tablespoons tomato paste',
      '2 cups beef broth',
      '3 tablespoons chili powder',
      '1 tablespoon ground cumin',
      '1 teaspoon smoked paprika',
      '1.5 teaspoons kosher salt',
      '1 cup shredded cheddar cheese',
    ],
  },
  {
    title: 'Pork Chops with Apples & Onions',
    category: 'Beef & Pork',
    description: 'Seared chops with sweet skillet apples and a cider pan sauce.',
    servings: 4,
    ingredients: [
      '4 bone-in pork chops',
      '2 apples, sliced',
      '1 yellow onion, sliced',
      '2 tablespoons unsalted butter',
      '2 tablespoons olive oil',
      '1/2 cup chicken broth',
      '2 tablespoons apple cider vinegar',
      '1 tablespoon fresh thyme',
      '1 teaspoon kosher salt',
      '1/2 teaspoon black pepper',
    ],
  },
  {
    title: 'Korean Beef Bowls',
    category: 'Beef & Pork',
    description: 'Sweet-savoury ground beef over rice with quick cucumbers.',
    servings: 4,
    ingredients: [
      '1.5 pounds ground beef',
      '1.5 cups jasmine rice',
      '1 cucumber, thinly sliced',
      '3 green onions, sliced',
      '1/3 cup soy sauce',
      '3 tablespoons brown sugar',
      '1 tablespoon sesame oil',
      '1 tablespoon fresh ginger, grated',
      '4 cloves garlic, minced',
      '2 tablespoons rice vinegar',
      '1 tablespoon sesame seeds',
      '1 teaspoon red pepper flakes',
    ],
  },
  {
    title: 'Sausage & Peppers Skillet',
    category: 'Beef & Pork',
    description: 'One skillet, big flavour, good with bread or over polenta.',
    servings: 4,
    ingredients: [
      '1.5 pounds italian sausage',
      '3 bell peppers, sliced',
      '1 yellow onion, sliced',
      '4 cloves garlic, sliced',
      '1 (14.5 ounce) can diced tomatoes',
      '2 tablespoons olive oil',
      '1 teaspoon dried oregano',
      '1/2 teaspoon red pepper flakes',
      '1 teaspoon kosher salt',
      '2 tablespoons fresh basil, torn',
    ],
  },
  {
    title: "Shepherd's Pie",
    category: 'Beef & Pork',
    description: 'Savoury mince under a blanket of buttery mashed potato.',
    servings: 6,
    ingredients: [
      '2 pounds ground lamb',
      '3 pounds russet potatoes, peeled',
      '1/2 cup whole milk',
      '4 tablespoons unsalted butter',
      '1 yellow onion, diced',
      '3 carrots, diced',
      '1 cup frozen peas',
      '2 tablespoons tomato paste',
      '2 cups beef broth',
      '2 tablespoons worcestershire sauce',
      '1 tablespoon fresh thyme',
      '1.5 teaspoons kosher salt',
      '1/2 teaspoon black pepper',
    ],
  },
  {
    title: 'Carnitas Burrito Bowls',
    category: 'Beef & Pork',
    description: 'Crisped slow-cooked pork with rice, beans and all the toppings.',
    servings: 6,
    ingredients: [
      '3 pounds pork shoulder',
      '2 cups white rice',
      '2 cans black beans, drained',
      '2 limes, juiced',
      '1 white onion, quartered',
      '2 oranges, juiced',
      '1 bunch fresh cilantro, chopped',
      '1 cup salsa',
      '1 avocado, sliced',
      '1 tablespoon ground cumin',
      '2 teaspoons dried oregano',
      '1 tablespoon kosher salt',
    ],
  },

  // ---------------------------------------------------------------- Seafood
  {
    title: 'Sheet Pan Salmon & Vegetables',
    category: 'Seafood',
    description: 'Everything roasts together on one tray in twenty-five minutes.',
    servings: 2,
    ingredients: [
      '2 salmon fillets',
      '1 pound baby potatoes, halved',
      '1 bunch asparagus, trimmed',
      '1 red bell pepper, sliced',
      '3 tablespoons olive oil',
      '1 lemon, sliced',
      '2 cloves garlic, minced',
      '1 teaspoon dried thyme',
      '1 teaspoon kosher salt',
      '1/2 teaspoon black pepper',
      '1 tablespoon dijon mustard',
    ],
  },
  {
    title: 'Garlic Shrimp Scampi',
    category: 'Seafood',
    description: 'Garlic, butter, white wine and lemon — ready before the pasta is.',
    servings: 4,
    ingredients: [
      '1.5 pounds shrimp, peeled',
      '12 ounces linguine',
      '6 cloves garlic, minced',
      '4 tablespoons unsalted butter',
      '3 tablespoons olive oil',
      '1/2 cup dry white wine',
      '1 lemon, juiced',
      '3 tablespoons fresh parsley, chopped',
      '1/2 teaspoon red pepper flakes',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'Blackened Fish Tacos',
    category: 'Seafood',
    description: 'Spice-crusted white fish with cabbage slaw and lime crema.',
    servings: 4,
    ingredients: [
      '1.5 pounds tilapia fillets',
      '8 corn tortillas',
      '3 cups shredded cabbage',
      '1/2 cup sour cream',
      '2 limes, juiced',
      '1/4 cup fresh cilantro, chopped',
      '1 avocado, sliced',
      '2 tablespoons olive oil',
      '1 tablespoon smoked paprika',
      '1 teaspoon cayenne pepper',
      '1 teaspoon garlic powder',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'Lemon Butter Cod',
    category: 'Seafood',
    description: 'Delicate baked cod with a lemon butter sauce and green beans.',
    servings: 4,
    ingredients: [
      '4 cod fillets',
      '1 pound green beans, trimmed',
      '4 tablespoons unsalted butter',
      '2 lemons, juiced',
      '3 cloves garlic, minced',
      '2 tablespoons olive oil',
      '2 tablespoons fresh parsley, chopped',
      '1 teaspoon kosher salt',
      '1/2 teaspoon black pepper',
    ],
  },
  {
    title: 'Shrimp Fried Rice',
    category: 'Seafood',
    description: 'The best use for yesterday’s rice, done in fifteen minutes.',
    servings: 4,
    ingredients: [
      '1 pound shrimp, peeled',
      '4 cups cooked white rice',
      '3 eggs, beaten',
      '1 cup frozen peas',
      '2 carrots, diced',
      '3 green onions, sliced',
      '3 cloves garlic, minced',
      '3 tablespoons soy sauce',
      '1 tablespoon sesame oil',
      '2 tablespoons vegetable oil',
      '1 tablespoon fresh ginger, grated',
    ],
  },
  {
    title: 'Tuna Poke Bowls',
    category: 'Seafood',
    description: 'No cooking at all — just slicing and a five-minute marinade.',
    servings: 2,
    ingredients: [
      '12 ounces sushi-grade tuna, cubed',
      '2 cups cooked sushi rice',
      '1 avocado, sliced',
      '1 cucumber, diced',
      '2 green onions, sliced',
      '3 tablespoons soy sauce',
      '1 tablespoon sesame oil',
      '1 tablespoon rice vinegar',
      '1 tablespoon sesame seeds',
      '1 teaspoon sriracha',
    ],
  },
  {
    title: 'Miso Glazed Salmon',
    category: 'Seafood',
    description: 'A sweet-salty miso glaze that caramelises under the grill.',
    servings: 4,
    ingredients: [
      '4 salmon fillets',
      '3 tablespoons miso paste',
      '2 tablespoons honey',
      '2 tablespoons soy sauce',
      '1 tablespoon rice vinegar',
      '1 tablespoon fresh ginger, grated',
      '1.5 cups jasmine rice',
      '1 pound bok choy, halved',
      '1 tablespoon sesame oil',
      '2 green onions, sliced',
    ],
  },

  // ------------------------------------------------------------- Vegetarian
  {
    title: 'Chickpea Coconut Curry',
    category: 'Vegetarian',
    description: 'Creamy, mildly spiced and almost entirely from the cupboard.',
    servings: 4,
    ingredients: [
      '2 tablespoons coconut oil',
      '1 yellow onion, diced',
      '3 cloves garlic, minced',
      '1 tablespoon fresh ginger, grated',
      '2 (15 ounce) cans chickpeas, drained',
      '1 (14 ounce) can coconut milk',
      '1 (14.5 ounce) can diced tomatoes',
      '3 cups baby spinach',
      '1.5 cups basmati rice',
      '1 tablespoon curry powder',
      '1 teaspoon ground turmeric',
      '1 teaspoon ground cumin',
      '1 teaspoon kosher salt',
      '1 lime, juiced',
    ],
  },
  {
    title: 'Black Bean Enchiladas',
    category: 'Vegetarian',
    description: 'Rolled, sauced and baked until the cheese bubbles.',
    servings: 4,
    ingredients: [
      '2 cans black beans, drained',
      '10 corn tortillas',
      '2 cups enchilada sauce',
      '2 cups shredded monterey jack',
      '1 yellow onion, diced',
      '1 red bell pepper, diced',
      '2 cloves garlic, minced',
      '1/4 cup fresh cilantro, chopped',
      '2 teaspoons ground cumin',
      '1 teaspoon chili powder',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'Crispy Tofu Stir Fry',
    category: 'Vegetarian',
    description: 'Cornstarch-crisped tofu with snap peas in a ginger soy glaze.',
    servings: 4,
    ingredients: [
      '2 blocks firm tofu, cubed',
      '3 tablespoons cornstarch',
      '1 pound snap peas',
      '2 bell peppers, sliced',
      '3 cloves garlic, minced',
      '1 tablespoon fresh ginger, grated',
      '1/3 cup soy sauce',
      '2 tablespoons rice vinegar',
      '1 tablespoon honey',
      '3 tablespoons vegetable oil',
      '1.5 cups jasmine rice',
      '1 tablespoon sesame seeds',
    ],
  },
  {
    title: 'Margherita Flatbreads',
    category: 'Vegetarian',
    description: 'Fifteen minutes from cupboard to dinner, with torn basil.',
    servings: 2,
    ingredients: [
      '2 flatbreads',
      '1 cup marinara sauce',
      '8 ounces fresh mozzarella, sliced',
      '1/4 cup fresh basil, torn',
      '2 tablespoons olive oil',
      '2 cloves garlic, minced',
      '1/2 teaspoon red pepper flakes',
      '1/2 teaspoon kosher salt',
    ],
  },
  {
    title: 'Stuffed Bell Peppers',
    category: 'Vegetarian',
    description: 'Peppers filled with herby rice, beans and melted cheese.',
    servings: 4,
    ingredients: [
      '4 bell peppers, halved',
      '1.5 cups cooked white rice',
      '1 can black beans, drained',
      '1 (14.5 ounce) can diced tomatoes',
      '1 cup shredded mozzarella',
      '1 yellow onion, diced',
      '3 cloves garlic, minced',
      '2 tablespoons olive oil',
      '1 teaspoon italian seasoning',
      '1 teaspoon ground cumin',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'Mushroom Risotto',
    category: 'Vegetarian',
    description: 'Worth the stirring — deeply savoury and properly creamy.',
    servings: 4,
    ingredients: [
      '1.5 cups arborio rice',
      '1 pound cremini mushrooms, sliced',
      '6 cups vegetable broth',
      '1 yellow onion, finely diced',
      '3 cloves garlic, minced',
      '1/2 cup dry white wine',
      '3/4 cup grated parmesan',
      '3 tablespoons unsalted butter',
      '2 tablespoons olive oil',
      '2 tablespoons fresh parsley, chopped',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'Falafel Bowls',
    category: 'Vegetarian',
    description: 'Crisp chickpea patties with cucumber salad and tahini sauce.',
    servings: 4,
    ingredients: [
      '2 (15 ounce) cans chickpeas, drained',
      '1 yellow onion, quartered',
      '4 cloves garlic',
      '1 bunch fresh parsley',
      '3 tablespoons all-purpose flour',
      '1/3 cup tahini',
      '2 lemons, juiced',
      '2 cucumbers, diced',
      '2 roma tomatoes, diced',
      '4 pita breads',
      '1 tablespoon ground cumin',
      '1 teaspoon ground coriander',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'Veggie Quesadillas',
    category: 'Vegetarian',
    description: 'A fridge-clearing dinner kids will actually eat.',
    servings: 4,
    ingredients: [
      '8 flour tortillas',
      '2 cups shredded cheddar cheese',
      '1 zucchini, diced',
      '1 red bell pepper, diced',
      '1 cup corn',
      '1 can black beans, drained',
      '2 tablespoons unsalted butter',
      '1 teaspoon ground cumin',
      '1 teaspoon chili powder',
      '1/2 cup salsa',
      '1/2 cup sour cream',
    ],
  },

  // ------------------------------------------------------------------ Pasta
  {
    title: 'Creamy Tomato Pasta',
    category: 'Pasta',
    description: 'Rosé sauce with a parmesan finish, done in one pot.',
    servings: 2,
    ingredients: [
      '8 ounces penne',
      '2 tablespoons olive oil',
      '3 cloves garlic, thinly sliced',
      '1 (28 ounce) can crushed tomatoes',
      '1/2 cup heavy cream',
      '1/2 cup grated parmesan',
      '1/4 cup fresh basil, torn',
      '1 teaspoon dried oregano',
      '1/2 teaspoon red pepper flakes',
      '1 teaspoon kosher salt',
      '1/2 teaspoon black pepper',
    ],
  },
  {
    title: 'Spaghetti Bolognese',
    category: 'Pasta',
    description: 'A proper long-simmered meat sauce, generous enough for leftovers.',
    servings: 6,
    ingredients: [
      '1.5 pounds ground beef',
      '1 pound spaghetti',
      '1 yellow onion, finely diced',
      '2 carrots, finely diced',
      '2 celery stalks, finely diced',
      '4 cloves garlic, minced',
      '1 (28 ounce) can crushed tomatoes',
      '3 tablespoons tomato paste',
      '1/2 cup whole milk',
      '1/2 cup dry red wine',
      '3 tablespoons olive oil',
      '1 teaspoon dried oregano',
      '1.5 teaspoons kosher salt',
      '1/2 cup grated parmesan',
    ],
  },
  {
    title: 'Pesto Pasta with Cherry Tomatoes',
    category: 'Pasta',
    description: 'Bright and summery, excellent warm or cold the next day.',
    servings: 4,
    ingredients: [
      '1 pound fusilli',
      '1 cup pesto',
      '2 cups cherry tomatoes, halved',
      '8 ounces fresh mozzarella, cubed',
      '1/4 cup fresh basil, torn',
      '2 tablespoons olive oil',
      '2 tablespoons pine nuts',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'Baked Ziti',
    category: 'Pasta',
    description: 'Layered with ricotta and baked until the top goes golden.',
    servings: 6,
    ingredients: [
      '1 pound ziti',
      '1 pound italian sausage',
      '3 cups marinara sauce',
      '15 ounces ricotta cheese',
      '2 cups shredded mozzarella',
      '1/2 cup grated parmesan',
      '1 yellow onion, diced',
      '3 cloves garlic, minced',
      '1 egg',
      '1/4 cup fresh basil, torn',
      '1 teaspoon dried oregano',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'Cacio e Pepe',
    category: 'Pasta',
    description: 'Four ingredients, no sauce to make — just pasta water and nerve.',
    servings: 2,
    ingredients: [
      '8 ounces spaghetti',
      '1.5 cups pecorino, finely grated',
      '2 teaspoons black pepper',
      '2 tablespoons unsalted butter',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'Lemon Garlic Shrimp Pasta',
    category: 'Pasta',
    description: 'Light, garlicky and on the table in under half an hour.',
    servings: 4,
    ingredients: [
      '1 pound shrimp, peeled',
      '12 ounces linguine',
      '5 cloves garlic, minced',
      '3 tablespoons unsalted butter',
      '3 tablespoons olive oil',
      '2 lemons, juiced',
      '3 cups baby spinach',
      '1/2 cup grated parmesan',
      '3 tablespoons fresh parsley, chopped',
      '1/2 teaspoon red pepper flakes',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'One-Pot Mac & Cheese',
    category: 'Pasta',
    description: 'No separate sauce pan, no draining, properly cheesy.',
    servings: 4,
    ingredients: [
      '1 pound elbow macaroni',
      '3 cups whole milk',
      '2 cups shredded cheddar cheese',
      '1 cup shredded gruyere',
      '3 tablespoons unsalted butter',
      '2 tablespoons all-purpose flour',
      '1 teaspoon dijon mustard',
      '1/2 teaspoon garlic powder',
      '1 teaspoon kosher salt',
      '1/4 teaspoon nutmeg',
    ],
  },
  {
    title: 'Pasta Primavera',
    category: 'Pasta',
    description: 'Whatever vegetables you have, lightly dressed in lemon and parmesan.',
    servings: 4,
    ingredients: [
      '1 pound penne',
      '1 zucchini, sliced',
      '1 yellow squash, sliced',
      '1 cup cherry tomatoes, halved',
      '1 bunch asparagus, trimmed',
      '3 cloves garlic, minced',
      '3 tablespoons olive oil',
      '1/2 cup grated parmesan',
      '1 lemon, juiced',
      '1/4 cup fresh basil, torn',
      '1 teaspoon kosher salt',
    ],
  },

  // --------------------------------------------------------- Soups & Stews
  {
    title: 'Chicken Tortilla Soup',
    category: 'Soups & Stews',
    description: 'Brothy and warming, piled high with crunchy tortilla strips.',
    servings: 6,
    ingredients: [
      '1.5 pounds chicken breast',
      '8 cups chicken broth',
      '1 (14.5 ounce) can diced tomatoes',
      '2 cans black beans, drained',
      '1 cup corn',
      '1 yellow onion, diced',
      '4 cloves garlic, minced',
      '6 corn tortillas, sliced',
      '2 limes, juiced',
      '1 avocado, sliced',
      '1/4 cup fresh cilantro, chopped',
      '1 tablespoon chili powder',
      '2 teaspoons ground cumin',
      '1.5 teaspoons kosher salt',
    ],
  },
  {
    title: 'Butternut Squash Soup',
    category: 'Soups & Stews',
    description: 'Velvety and just sweet enough, finished with a swirl of cream.',
    servings: 4,
    ingredients: [
      '1 butternut squash, cubed',
      '1 yellow onion, diced',
      '2 carrots, chopped',
      '4 cups vegetable broth',
      '1/2 cup heavy cream',
      '3 cloves garlic, minced',
      '2 tablespoons olive oil',
      '1 tablespoon fresh sage',
      '1/2 teaspoon nutmeg',
      '1 teaspoon kosher salt',
      '1/2 teaspoon black pepper',
    ],
  },
  {
    title: 'Beef Stew',
    category: 'Soups & Stews',
    description: 'Low and slow until the beef falls apart against a spoon.',
    servings: 6,
    ingredients: [
      '2.5 pounds beef chuck, cubed',
      '2 pounds russet potatoes, cubed',
      '4 carrots, chopped',
      '2 celery stalks, chopped',
      '1 yellow onion, diced',
      '4 cloves garlic, minced',
      '6 cups beef broth',
      '3 tablespoons tomato paste',
      '1 cup dry red wine',
      '3 tablespoons all-purpose flour',
      '2 tablespoons worcestershire sauce',
      '2 bay leaves',
      '1 tablespoon fresh thyme',
      '1.5 teaspoons kosher salt',
    ],
  },
  {
    title: 'Lentil Soup',
    category: 'Soups & Stews',
    description: 'Cheap, filling and freezes beautifully.',
    servings: 6,
    ingredients: [
      '2 cups red lentils',
      '8 cups vegetable broth',
      '1 yellow onion, diced',
      '3 carrots, diced',
      '2 celery stalks, diced',
      '4 cloves garlic, minced',
      '1 (14.5 ounce) can diced tomatoes',
      '3 cups baby spinach',
      '2 tablespoons olive oil',
      '1 lemon, juiced',
      '1 tablespoon ground cumin',
      '1 teaspoon ground turmeric',
      '1.5 teaspoons kosher salt',
    ],
  },
  {
    title: 'Minestrone',
    category: 'Soups & Stews',
    description: 'A whole garden in a bowl, with pasta for good measure.',
    servings: 6,
    ingredients: [
      '1 cup small pasta',
      '8 cups vegetable broth',
      '1 can cannellini beans, drained',
      '1 (28 ounce) can crushed tomatoes',
      '2 carrots, diced',
      '2 celery stalks, diced',
      '1 zucchini, diced',
      '1 yellow onion, diced',
      '4 cloves garlic, minced',
      '2 cups green beans, trimmed',
      '3 tablespoons olive oil',
      '1/2 cup grated parmesan',
      '1 teaspoon dried oregano',
      '1.5 teaspoons kosher salt',
    ],
  },
  {
    title: 'Thai Coconut Chicken Soup',
    category: 'Soups & Stews',
    description: 'Fragrant tom kha with lime, ginger and coconut milk.',
    servings: 4,
    ingredients: [
      '1 pound chicken breast, sliced',
      '2 (14 ounce) cans coconut milk',
      '4 cups chicken broth',
      '8 ounces shiitake mushrooms, sliced',
      '2 tablespoons fresh ginger, grated',
      '2 limes, juiced',
      '3 tablespoons fish sauce',
      '2 tablespoons red curry paste',
      '1 tablespoon brown sugar',
      '1/4 cup fresh cilantro, chopped',
      '3 green onions, sliced',
    ],
  },
  {
    title: 'Broccoli Cheddar Soup',
    category: 'Soups & Stews',
    description: 'Thick, cheesy and begging for a crusty loaf.',
    servings: 4,
    ingredients: [
      '1.5 pounds broccoli florets',
      '3 cups shredded cheddar cheese',
      '4 cups chicken broth',
      '2 cups whole milk',
      '1 yellow onion, diced',
      '2 carrots, grated',
      '4 tablespoons unsalted butter',
      '1/4 cup all-purpose flour',
      '1 teaspoon dijon mustard',
      '1 teaspoon kosher salt',
      '1/2 teaspoon black pepper',
    ],
  },

  // -------------------------------------------------------------- Breakfast
  {
    title: 'Veggie Breakfast Scramble',
    category: 'Breakfast',
    description: 'Soft eggs with peppers, spinach and feta.',
    servings: 2,
    ingredients: [
      '6 eggs',
      '3 cups baby spinach',
      '1 red bell pepper, diced',
      '1/2 cup feta',
      '2 tablespoons unsalted butter',
      '2 green onions, sliced',
      '1/2 teaspoon kosher salt',
      '1/4 teaspoon black pepper',
    ],
  },
  {
    title: 'Overnight Oats',
    category: 'Breakfast',
    description: 'Assembled the night before, eaten straight from the jar.',
    servings: 2,
    ingredients: [
      '1 cup rolled oats',
      '1 cup whole milk',
      '1/2 cup greek yogurt',
      '2 tablespoons chia seeds',
      '2 tablespoons honey',
      '1 cup blueberries',
      '1/4 cup almonds, chopped',
      '1/2 teaspoon ground cinnamon',
    ],
  },
  {
    title: 'Buttermilk Pancakes',
    category: 'Breakfast',
    description: 'Tall, fluffy and worth getting the buttermilk for.',
    servings: 4,
    ingredients: [
      '2 cups all-purpose flour',
      '2 cups buttermilk',
      '2 eggs',
      '3 tablespoons sugar',
      '2 teaspoons baking powder',
      '1 teaspoon baking soda',
      '4 tablespoons unsalted butter, melted',
      '1 teaspoon vanilla extract',
      '1/2 teaspoon kosher salt',
      '1/2 cup maple syrup',
    ],
  },
  {
    title: 'Breakfast Burritos',
    category: 'Breakfast',
    description: 'Make a batch on Sunday and freeze them for the week.',
    servings: 4,
    ingredients: [
      '8 eggs',
      '4 large flour tortillas',
      '1 pound breakfast sausage',
      '2 russet potatoes, diced',
      '1.5 cups shredded cheddar cheese',
      '1 red bell pepper, diced',
      '1/2 cup salsa',
      '2 tablespoons vegetable oil',
      '1 teaspoon kosher salt',
      '1/2 teaspoon black pepper',
    ],
  },
  {
    title: 'Greek Yogurt Parfaits',
    category: 'Breakfast',
    description: 'Three minutes, no cooking, and it feels like a treat.',
    servings: 2,
    ingredients: [
      '2 cups greek yogurt',
      '1 cup granola',
      '1 cup strawberries, sliced',
      '1 cup blueberries',
      '3 tablespoons honey',
      '2 tablespoons chia seeds',
    ],
  },
  {
    title: 'Shakshuka',
    category: 'Breakfast',
    description: 'Eggs poached in a spiced tomato sauce, eaten with bread.',
    servings: 4,
    ingredients: [
      '6 eggs',
      '1 (28 ounce) can crushed tomatoes',
      '1 yellow onion, diced',
      '1 red bell pepper, diced',
      '4 cloves garlic, minced',
      '1/2 cup feta',
      '3 tablespoons olive oil',
      '1/4 cup fresh parsley, chopped',
      '1 tablespoon smoked paprika',
      '1 teaspoon ground cumin',
      '1/2 teaspoon cayenne pepper',
      '1 teaspoon kosher salt',
      '1 baguette',
    ],
  },
  {
    title: 'Avocado Toast with Eggs',
    category: 'Breakfast',
    description: 'Good bread, ripe avocado, a jammy egg and plenty of chilli.',
    servings: 2,
    ingredients: [
      '4 slices sourdough',
      '2 avocados',
      '4 eggs',
      '1 lemon, juiced',
      '2 tablespoons olive oil',
      '1/2 teaspoon red pepper flakes',
      '1 teaspoon flaky salt',
      '1/4 teaspoon black pepper',
    ],
  },

  // -------------------------------------------------------- Salads & Bowls
  {
    title: 'Greek Salad with Chicken',
    category: 'Salads & Bowls',
    description: 'Crunchy, salty and substantial enough to be dinner.',
    servings: 4,
    ingredients: [
      '1.5 pounds chicken breast',
      '2 cucumbers, chopped',
      '3 roma tomatoes, chopped',
      '1 red onion, thinly sliced',
      '1 cup kalamata olives',
      '1.5 cups feta',
      '1/3 cup olive oil',
      '2 lemons, juiced',
      '1 tablespoon red wine vinegar',
      '1 teaspoon dried oregano',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'Southwest Quinoa Bowls',
    category: 'Salads & Bowls',
    description: 'Protein-heavy meal-prep bowls with a smoky lime dressing.',
    servings: 4,
    ingredients: [
      '1.5 cups quinoa',
      '2 cans black beans, drained',
      '1.5 cups corn',
      '2 bell peppers, diced',
      '1 red onion, diced',
      '2 avocados, sliced',
      '2 limes, juiced',
      '1/4 cup olive oil',
      '1/4 cup fresh cilantro, chopped',
      '1 tablespoon ground cumin',
      '1 teaspoon smoked paprika',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'Caesar Salad with Croutons',
    category: 'Salads & Bowls',
    description: 'Homemade croutons make all the difference here.',
    servings: 4,
    ingredients: [
      '3 romaine hearts, chopped',
      '1 cup grated parmesan',
      '4 slices sourdough, cubed',
      '1/2 cup mayonnaise',
      '3 tablespoons olive oil',
      '2 lemons, juiced',
      '4 anchovy fillets',
      '2 cloves garlic, minced',
      '1 teaspoon dijon mustard',
      '1/2 teaspoon black pepper',
    ],
  },
  {
    title: 'Mediterranean Grain Bowls',
    category: 'Salads & Bowls',
    description: 'Farro, roasted vegetables and a garlicky yogurt sauce.',
    servings: 4,
    ingredients: [
      '1.5 cups farro',
      '2 zucchini, sliced',
      '1 red onion, sliced',
      '2 cups cherry tomatoes',
      '1 cup greek yogurt',
      '1 cup feta',
      '1/3 cup olive oil',
      '2 lemons, juiced',
      '3 cloves garlic, minced',
      '1/4 cup fresh parsley, chopped',
      '1 teaspoon dried oregano',
      '1 teaspoon kosher salt',
    ],
  },
  {
    title: 'Thai Peanut Crunch Salad',
    category: 'Salads & Bowls',
    description: 'Shredded vegetables and a peanut dressing that keeps for days.',
    servings: 4,
    ingredients: [
      '4 cups shredded cabbage',
      '3 carrots, grated',
      '1 red bell pepper, sliced',
      '3 green onions, sliced',
      '1/2 cup peanut butter',
      '3 tablespoons soy sauce',
      '2 limes, juiced',
      '2 tablespoons honey',
      '1 tablespoon sesame oil',
      '1 tablespoon fresh ginger, grated',
      '1/2 cup peanuts, chopped',
      '1/4 cup fresh cilantro, chopped',
    ],
  },
  {
    title: 'Cobb Salad',
    category: 'Salads & Bowls',
    description: 'Everything in neat rows, then thoroughly mixed up anyway.',
    servings: 4,
    ingredients: [
      '2 romaine hearts, chopped',
      '1 pound cooked chicken breast, sliced',
      '6 slices bacon, cooked',
      '4 eggs, hard boiled',
      '2 avocados, sliced',
      '2 cups cherry tomatoes, halved',
      '1 cup blue cheese',
      '1/3 cup olive oil',
      '2 tablespoons red wine vinegar',
      '1 teaspoon dijon mustard',
      '1/2 teaspoon black pepper',
    ],
  },
  {
    title: 'Burrito Bowls with Cilantro Lime Rice',
    category: 'Salads & Bowls',
    description: 'All the burrito fillings, none of the structural failure.',
    servings: 4,
    ingredients: [
      '2 cups white rice',
      '1.5 pounds chicken thighs',
      '2 cans black beans, drained',
      '1.5 cups corn',
      '2 limes, juiced',
      '1/2 cup fresh cilantro, chopped',
      '1 cup salsa',
      '1 cup shredded monterey jack',
      '2 avocados, sliced',
      '1/2 cup sour cream',
      '2 tablespoons olive oil',
      '1 tablespoon chili powder',
      '2 teaspoons ground cumin',
      '1 teaspoon kosher salt',
    ],
  },
];
